name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

exclude-labels:
  - skip changelog
  - release

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'

replacers:
  # Remove conventional commit prefixes (feat:, fix:, etc.)
  - search: '/- (build|chore|ci|docs|feat|fix|perf|refactor|release|test)(\(.*\))?(\!)?: /g'
    replace: '- '

autolabeler:
  - label: breaking
    title:
      - '/^.*!:/'
  - label: enhancement
    title:
      - '/^feat/'
  - label: fix
    title:
      - '/^fix/'
  - label: performance
    title:
      - '/^perf/'
  - label: documentation
    title:
      - '/^docs/'
  - label: build
    title:
      - '/^build|ci/'
  - label: internal
    title:
      - '/^chore|refactor|test/'

version-resolver:
  major:
    labels: [ breaking ]
  minor:
    labels: [ enhancement, performance ]
  patch:
    labels: [ fix, documentation, build, internal ]
  default: patch

categories:
  - title: "ðŸ’¥ Breaking changes"
    labels: [ breaking ]
  - title: "ðŸš€ Performance improvements"
    labels: [ performance ]
  - title: "âœ¨ Enhancements"
    labels: [ enhancement ]
  - title: "ðŸž Bug fixes"
    labels: [ fix ]
  - title: "ðŸ“– Documentation"
    labels: [ documentation ]
  - title: "ðŸ“¦ Build & CI"
    labels: [ build ]
  - title: "ðŸ› ï¸ Internal changes"
    labels: [ internal ]

  - title: "ðŸ—‚ï¸ Other changes"
    labels: [ "*" ]                # wildcard (= any label or none)
    exclude-labels: # prevent duplicates; list ALL labels used above
      - breaking
      - performance
      - enhancement
      - fix
      - documentation
      - build
      - internal

template: |
  ## Changes
  $CHANGES

  ---
  ðŸ§¡ Thank you to all our contributors!
  $CONTRIBUTORS
